### ISSUE TITLE
rebuild/push images to update bgpstream dependency repo issue

### ISSUE THREAD

**Issue by digizeph** [slowr/artemis-base-images#2]
bgpstream has a dependency that has switched to a new package repo host, and its previous host recently deprecated. This causes the apt-update fails because the source list no-long work. I have updated the dependent bgpstream images but I believe you still need to rebuild and repush the images accordingly.

Specifically, this file: https://github.com/slowr/artemis-base-images/blob/master/monitor/Dockerfile

**Comment by slowr** [comment]
I rebuilt the image to have the newest version at `mavromat/artemis-base-images:monitor-1.0.2`. I will create a PR on artemis repo to update to this version as well.
